apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: training-episerver
  title: Training Episerver
  description: <!-- IGNORE THE HTML BLOCK BELOW, THE INTERESTING PART IS AFTER IT
    -->
  annotations:
    backstage.io/source-location: url:https://dev.azure.com/euromonitor/Software%20Engineering%20Team%20Training/_git/Training-Episerver
    dev.azure.com/project-repo: Software Engineering Team Training/Training-Episerver
    dev.azure.com/build-definition: Training-Episerver-CI
    backstage.io/techdocs-ref: dir:.
  links:
  - title: Azure DevOps Repository
    url: https://dev.azure.com/euromonitor/Software%20Engineering%20Team%20Training/_git/Training-Episerver
    icon: code
spec:
  type: service
  lifecycle: development
  owner: group:default/software-engineering
